### ISSUE TITLE
PR should be marked as `need-rebase` if it is not mergable

### ISSUE THREAD

**Issue by dbasunag** [myk-org/github-webhook-server#423]
Currently PR is marked with `need-rebase` if it is behind HEAD(https://github.com/myk-org/github-webhook-server/blob/main/webhook_server_container/libs/github_api.py#L1166). This many times marks PRs that are otherwise mergable, as `can-not-be-merged` due to addition of `needs-rebase` label to it. However, based on API docs: https://docs.github.com/en/rest/guides/using-the-rest-api-to-interact-with-your-git-database?apiVersion=2022-11-28#checking-mergeability-of-pull-requests, it recommends checking ```mergeable attribute is true or false``` to determine meargability of a PR. I see the same being used in https://github.com/kubernetes/test-infra/blob/master/gubernator/github/classifier.py#L221 (used by kubevirt and openshift repos).

Can we use `mergeable` property to be not true before adding `needs-rebase`? For conflicts it makes sense to check `merge_state == "dirty"`.

**Comment by dbasunag** [comment]
My proposed solution is:
``` def label_pull_request_by_merge_state(self, _sleep=30):
        if _sleep:
            self.app.logger.info(f"{self.log_prefix} Sleep for 30 seconds before checking merge state")
            time.sleep(_sleep)

        merge_state = self.pull_request.mergeable_state
        mergable = self.pull_request.mergeable
        self.app.logger.info(f"{self.log_prefix} Mergeable state is {merge_state}, PR mergable: {mergable}")

        if not mergable:
            self._add_label(label=NEEDS_REBASE_LABEL_STR)
        else:
            self._remove_label(label=NEEDS_REBASE_LABEL_STR)

        if merge_state == "dirty":
            self._add_label(label=HAS_CONFLICTS_LABEL_STR)
        else:
            self._remove_label(label=HAS_CONFLICTS_LABEL_STR)```

**Comment by myakove** [comment]
The solution should be user configurable labels to set PR as can-be-merged. 

can-be-merged-required-ladels:
    - label1
    - label2

If not set use the current behavior

**Comment by myakove** [comment]
For now `can-be-merged` will ignore `behind`  state.
`needs-rebase` label will still be added to the PR if the PR is in behind state, but this will not affect `can-be-merged` label
