### ISSUE TITLE
Track PRs in jira

### ISSUE THREAD

**Issue by rnetser** [myk-org/github-webhook-server#427]
When a new PR is opened:
-  open a new story in jira; assigned to the PR owner
- add a label with the jira story id to the pr

When a reviewer adds a review:
- Open and close a sub-task, and assign to the reviewer

When there's a new commit:
- open  and close a sub-task, and assign to the PR owner; add commit hash in the description

When a PR is merged:
- Close the jira story as "Done"

When a PR is closed:
- Close the jira story as "Won't do"

**Comment by myakove** [comment]
Done
