### ISSUE TITLE
Wrong set of reviewers getting assigned to a PR

### ISSUE THREAD

**Issue by dbasunag** [myk-org/github-webhook-server#521]
Sample PR: https://github.com/RedHatQE/cnv-tests/pull/1029
Owners file: https://github.com/RedHatQE/cnv-tests/blob/main/OWNERS

**Comment by dbasunag** [comment]
Another one https://github.com/RedHatQE/cnv-tests/pull/1133

**Comment by myakove** [comment]
@dbasunag 
Is this issue still valid?

**Comment by myakove** [comment]
closing since no response from the reposter.
